(clear)
(load Ejercicio2noCond.clp)
(reset)
(assert(mover cabra))
(run)
(assert(mover granjero))
(run)
(assert(mover lobo))
(run)
(assert(mover cabra))
(run)
(assert(mover col))
(run)
(assert(mover granjero))
(run)
(assert(mover cabra))
(run)